# Generated by Django 5.2 on 2025-05-31 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='building_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='road_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('product_status', models.CharField(default='order placed', max_length=30)),
                ('order_date', models.DateTimeField()),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.product')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.signup')),
            ],
        ),
    ]
