# Generated by Django 5.2 on 2025-06-04 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.signup')),
            ],
        ),
    ]
